# Generated by Django 3.2.12 on 2024-04-15 09:08

import client.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, validators=[client.validate.validate_account_number], verbose_name='номер счета')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='отчество')),
                ('date_birth', models.DateField(validators=[client.validate.validate_birth_date], verbose_name='дата рождения')),
                ('inn', models.CharField(max_length=12, unique=True, validators=[client.validate.validate_inn], verbose_name='инн')),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('Отказ', 'Отказ'), ('Сделка закрыта', 'Сделка закрыта'), ('Не в работе', 'Не в работе')], default='Не в работе', max_length=14, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
